# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Ensure noexec is enabled in /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    regexp: '^(?!#)[\s]*Defaults.*[\s]+noexec[\s]*.*$'
    line: 'Defaults noexec'
