# platform = multi_platform_sle
- name: Check 'UTC' timezone is set
  shell: timedatectl status | grep -i 'Time zone'| grep -iv 'UTC\|GMT'
  register: check_tz
  failed_when: "check_tz.rc not in [ 0 , 1 ]"
 
- name: Configure OS to use 'UTC' timezone
  command: timedatectl set-timezone UTC 
  become: yes
  when: check_tz.rc == 0
