# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Ensure all AppArmor Profiles are reloaded
  ansible.builtin.shell: apparmor_parser -q -r /etc/apparmor.d/

- name:  Ensure all AppArmor Profiles are enforcing
  ansible.builtin.shell: aa-enforce /etc/apparmor.d/*

- name: Collect unconfined processes 
  ansible.builtin.shell: aa-unconfined
  register: unconfined_processes

- name: Provide details about unconfined processes 
  ansible.builtin.shell: echo "The process {{ item }} may need to have a profile created or activated for them and then be restarted."
  with_items: "{{ unconfined_processes.stdout_lines }}"
  when: unconfined_processes.stdout_lines | length > 0
