# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ ansible_instantiate_variables("rsyslog_remote_loghost_address") }}}

- name: Check for duplicate values in master configuration
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    create: false
    regexp: "^\\*\\.\\*"
    state: absent
  check_mode: true
  changed_when: false
  register: dupes_master

- name: Deduplicate values from rsyslog master configuration
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    create: false
    regexp: "^\\*\\.\\*"
    state: absent
  when: dupes_master.found is defined and dupes_master.found > 1

- name: Collect all config rsyslog files which configure Compress
  ansible.builtin.find:
    paths: /etc/rsyslog.d/
    contains: "^\\*\\.\\*"
    patterns: "*.conf"
  register: rsyslog_dropin_config_files

- name: Deduplicate values from rsyslog dropin configuration
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    create: false
    regexp: "^\\*\\.\\*"
    state: absent
  loop: "{{  rsyslog_dropin_config_files.files }}"
  
- name: "Set rsyslog remote loghost"
  lineinfile:
    dest: /etc/rsyslog.d/remote.conf
    regexp: "^\\*\\.\\*"
    line: "*.* @@{{ rsyslog_remote_loghost_address }}"
    create: yes
