# platform = Red Hat Enterprise Linux 8,Fedora
# reboot = true
# strategy = restrict
# complexity = low
# disruption = low

- name: "{{{ rule_title }}}: Existing value check"
  lineinfile:
    path: /etc/crypto-policies/back-ends/gnutls.config
    create: false
    regexp: '\+VERS-ALL:-VERS-DTLS0\.9:-VERS-SSL3\.0:-VERS-TLS1\.0:-VERS-TLS1\.1:-VERS-DTLS1\.0'
    state: absent
  check_mode: true
  changed_when: false
  register: gnutls

- name: "{{{ rule_title }}}"
  replace:
    path: /etc/crypto-policies/back-ends/gnutls.config
    regexp: (\+VERS-ALL(?::-VERS-[A-Z]+\d\.\d)+)
    replace: +VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0
  when: (gnutls.found is defined and gnutls.found != 1) or gnutls.msg == "file not present"
