# platform = multi_platform_rhel, multi_platform_fedora
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- (xccdf-var var_sssd_ldap_tls_ca_dir)

- name: "Test for domain group"
  shell: grep '\s*\[domain\/[^]]*]' /etc/sssd/sssd.conf
  register: test_grep_domain
  ignore_errors: yes
  changed_when: False

- name: "Add default domain group and set CA directory (if no domain there)"
  lineinfile:
    path: /etc/sssd/sssd.conf
    create: yes
    line: "[domain/default]\nldap_tls_cacertdir = {{ var_sssd_ldap_tls_ca_dir }}\n"
    mode: 0600
  when: test_grep_domain.stdout == ""

- name: "Configure LDAPs path to CA directory"
  ini_file:
    path: /etc/sssd/sssd.conf
    section: "{{ test_grep_domain.stdout | regex_replace('\\[(.*)\\]','\\1') }}"
    option: ldap_tls_cacertdir
    value: "{{ var_sssd_ldap_tls_ca_dir }}"
    create: yes
    mode: 0600
  when: test_grep_domain.stdout != ""
