# platform = multi_platform_ocp
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- (xccdf-var var_etcd_client_cert_auth)

- name: "@RULE_TITLE@"
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_CLIENT_CERT_AUTH='
    line: "ETCD_CLIENT_CERT_AUTH={{ var_etcd_client_cert_auth }}"
    create: yes
  tags:
    @ANSIBLE_TAGS@
