exclude_paths:
  - '*'
  - "build/**"
  - "chromium/**"
  - "cmake/**"
  - "CMakeFiles/**"
  - "debian8/**"
  - "docs/**"
  - "eap6/**"
  - "fedora/**"
  - "firefox/**"
  - "fuse6/**"
  - "jboss_eap6/**"
  - "jboss_fuse6/**"
  - "jre/**"
  - "ocp3/**"
  - "ol7/**"
  - "opensuse/**"
  - "rhel6/**"
  - "rhel7/**"
  - "rhel-osp7/**"
  - "rhosp7/**"
  - "sle11/**"
  - "sle12/**"
  - "ubuntu14/**"
  - "ubuntu1404/**"
  - "ubuntu16/**"
  - "ubuntu1604/**"
  - "webmin/**"
  - "wrlinux/**"

  - "shared/checks/**"
  - "shared/fixes/**"
  - "shared/guide/**"
  - "shared/images/**"
  - "shared/misc/**"
  - "shared/references/**"
  - "shared/transforms/**"

  - "tests/data/**"
  - "tests/kickstarts/**"
  - "tests/logs/**"
  - "tests/unit/**"
