---
version: "2"
checks:
  file-lines:
    config:
      threshold: 400

plugins:
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
  shellcheck:
    enabled: true

exclude_patterns:
  - "**/"
  - "*"
  - ".*"
  - ".*/"

  - "!build-scripts/*.py"
  - "!ssg/*.py"
  - "!ssg/**/*.py"
  - "!utils/*.py"

  - "!shared/**/*.py"

  - "!*.md"
  - "!**/*.md"
  - "!.*/*.md"

  - "!tests/*.sh"
  - "!tests/shared/*.sh"
  - "!utils/*.sh"
  - "!build_product"

  - "!tests/*.py"
  - "!tests/ssg_test_suite/*.py"
  - "!tests/ssg_test_suite/**/*.py"
