sudo: required

services:
    - docker

language: python

matrix:
    include:
        - env: BASE_IMAGE="Fedora"
          before_install:
            - docker build --no-cache --tag ssg:latest -f Dockerfile .
          script:
            - docker run ssg:latest
        - env: BASE_IMAGE="Ubuntu"
          before_install:
            - docker build --no-cache --tag ssg_ubuntu:latest -f Dockerfile_ubuntu .
          script:
            - docker run ssg_ubuntu:latest
