product: opensuse
full_name: openSUSE
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "zypper"

init_system: "systemd"

cpes:
  - "cpe:/o:opensuse:leap:42.1"
  - "cpe:/o:opensuse:leap:42.2"
  - "cpe:/o:opensuse:leap:42.3"
  - "cpe:/o:opensuse:leap:15.0"
