# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- name: "Force dconf to use the textfiles instead of a binary DB"
  lineinfile:
    path: '/etc/dconf/profile/user'
    regexp: '^service-db:keyfile/user$'
    line: 'service-db:keyfile/user'
    insertbefore: 'BOF'
    create: yes
  tags:
    @ANSIBLE_TAGS@
  @ANSIBLE_ENSURE_PLATFORM@

