# platform = Red Hat Enterprise Linux 8,Red Hat Enterprise Linux 9,multi_platform_fedora,multi_platform_ol
# reboot = false
# strategy = configure
# complexity = low
# disruption = medium

{{{ ansible_instantiate_variables("var_authselect_profile") }}}

- name: Select authselect profile
  ansible.builtin.command:
    cmd: authselect select "{{ var_authselect_profile }}"
  register: result_authselect_select
  failed_when: result_authselect_select.rc not in [0, 4]

- name: Verify if PAM has been altered
  ansible.builtin.command:
    cmd: rpm -qV pam
  register: result_altered_authselect
  ignore_errors: yes
  # return:
  # - 0 if no alterations
  # - otherwise: number of failured packages
  #   We have 1 package here. So 1 it is.
  failed_when: result_altered_authselect.rc not in [0, 1]
  args:
    warn: False
  when:
    - result_authselect_select is failed

- name: Informative message based on the authselect integrity check
  ansible.builtin.assert:
    that:
      - result_altered_authselect is success
    fail_msg:
      - Files in the 'pam' package have been altered, so the authselect configuration won't be forced.

- name: Force authselect profile select
  ansible.builtin.command:
    cmd: authselect select --force "{{ var_authselect_profile }}"
  when:
    - result_altered_authselect is success
    - result_authselect_select is failed
