# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- (xccdf-var var_etcd_auto_tls)

- name: "@RULE_TITLE@"
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_AUTO_TLS='
    line: "ETCD_AUTO_TLS={{ var_etcd_auto_tls }}"
    create: yes
  tags:
    @ANSIBLE_TAGS@
