product: rhel7
full_name: Red Hat Enterprise Linux 7
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

cpes:
  - "cpe:/o:redhat:enterprise_linux:7"
  - "cpe:/o:redhat:enterprise_linux:7::client"
  - "cpe:/o:redhat:enterprise_linux:7::computenode"
