product: susemicro5
full_name: SUSE Linux Enterprise Micro OS 5.x
type: platform

major_version_ordinal: 5

benchmark_id: SUSEMICRO5
benchmark_root: "../../linux_os/guide"

profiles_root: "./profiles"

init_system: "systemd"

pkg_manager: "zypper"
pkg_manager_config_file: "/etc/zypp/zypp.conf"


aide_bin_path: "/usr/bin/aide"

cpes_root: "../../shared/applicability"
cpes:
  - susemicro-5.2:
      name: "cpe:/o:suse:sle-microos:5.2"
      title: "SLE MicroOS 5.2"
      check_id: installed_OS_is_susemicro5

  - susemicro-5.3:
      name: "cpe:/o:suse:sle-microos:5.3"
      title: "SLE MicroOS 5.3"
      check_id: installed_OS_is_susemicro5

  - susemicro-5.4:
      name: "cpe:/o:suse:sle-microos:5.4"
      title: "SLE Micro 5.5"
      check_id: installed_OS_is_susemicro5

  - susemicro-5.5:
      name: "cpe:/o:suse:sle-microos:5.5"
      title: "SLE Micro 5.5"
      check_id: installed_OS_is_susemicro5

platform_package_overrides:
  login_defs: "shadow"
  grub2: "grub2"
  sssd: "sssd"
  passwd: "shadow"

sysctl_remediate_drop_in_file: "true"
journald_conf_dir_path: /etc/systemd/journal.conf.d