product: sle11

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "upstart"

cpes:
  - "cpe:/o:suse:linux_enterprise_server:11"

full_name: SUSE Linux Enterprise 11
