# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ kubernetes_machine_config(PATH='/etc/ssh/sshd_config', MODE='0600', SOURCE=sshd_config_source()) }}}
