product: eap6
full_name: JBoss EAP 6
type: product

benchmark_root: "./guide"

profiles_root: "./profiles"

cpes:
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.0.0"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.0.1"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.1.0"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.1.1"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.2.0"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.2.1"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.2.2"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.2.3"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.2.4"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.3.0"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.3.1"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.3.2"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.3.3"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.0"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.1"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.2"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.3"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.4"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.5"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.6"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.7"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.8"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.9"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.10"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.11"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.12"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.13"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.14"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.15"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.16"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.17"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.18"
  - "cpe:/a:redhat:jboss_enterprise_application_platform:6.4.19"
