product: ol7
full_name: Oracle Linux 7
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "systemd"

cpes:
  ol7:
    name: "cpe:/o:oracle:linux:7"
    title: "Oracle Linux 7"
    check_id: installed_OS_is_ol7_family
