# platform = multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- (xccdf-var var_system_crypto_policy)

- name: "@RULE_TITLE@"
  lineinfile:
    path: /etc/crypto-policies/config
    regexp: '^(?!#)(\S+)$'
    line: "{{ var_system_crypto_policy }}"
    create: yes
  tags:
    @ANSIBLE_TAGS@
