product: jre

benchmark_root: "./guide"

profiles_root: "./profiles"

cpes:
  - "cpe:/a:oracle:jre:"
  - "cpe:/a:sun:jre:"
  - "cpe:/a:redhat:openjdk:"
  - "cpe:/a:ibm:jre:"

full_name: Java Runtime Environment
