# platform = Red Hat Enterprise Linux 8
# reboot = true
# strategy = restrict
# complexity = low
# disruption = low

- name: "Ensure system crypto policy has OpenSSL library using TLS encryption"
  lineinfile:
    path: "/etc/crypto-policies/back-ends/opensslcnf.config"
    line: "MinProtocol = TLSv1.2"
    create: yes
    insertafter: EOF

- name: "Update system crypto policy for changes to take effect"
  command:
    cmd: "update-crypto-policies"
