product: sle12

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

init_system: "systemd"

pkg_manager: "yum"

cpes:
  - "cpe:/o:suse:linux_enterprise_server:12"

full_name: SUSE Linux Enterprise 12
