# platform = Red Hat Enterprise Linux 8,multi_platform_fedora

{{{ ansible_set_config_file(file="/etc/rsyslog.d/encrypt.conf",
                    parameter="\$DefaultNetstreamDriver", value="gtls", create=true, separator=" ", separator_regex=" ")
}}}
