# platform = Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8,multi_platform_fedora,multi_platform_rhv,multi_platform_ol,multi_platform_sle
# reboot = false
# strategy = configure
# complexity = low
# disruption = medium
- name: "Test for domain group"
  command: grep '^\s*\[domain\/[^]]*]' /etc/sssd/sssd.conf
  register: test_grep_domain
  ignore_errors: yes
  changed_when: False
  check_mode: no

- name: "Add default domain group (if no domain there)"
  ini_file:
    path: /etc/sssd/sssd.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
    mode: 0600
  with_items:
    - { section: sssd, option: domains, value: default}
    - { section: domain/default, option: id_provider, value: files }
  when:
    - test_grep_domain.stdout is defined
    - test_grep_domain.stdout | length < 1

- name: "Enable Smartcards in SSSD"
  ini_file:
    dest: /etc/sssd/sssd.conf
    section: pam
    option: pam_cert_auth
    value: 'true'
    create: yes
    mode: 0600

{{% if product in ["ol8", "rhel8"] %}}
- name: Check for expected pam_sss.so entry in system-auth
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/system-auth"
    create: no
    regexp: '^\s*auth.*sufficient.*pam_sss\.so.*try_cert_auth.*$'
    state: absent
  check_mode: true
  changed_when: false
  register: result_pam_try_cert_auth_present_system_auth

- name: Check for expected pam_sss.so entry in smartcard-auth
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/smartcard-auth"
    create: no
    regexp: '^\s*auth.*sufficient.*pam_sss\.so.*try_cert_auth.*$'
    state: absent
  check_mode: true
  changed_when: false
  register: result_pam_try_cert_auth_present_smartcard_auth

- name: Check if system relies on authselect
  ansible.builtin.stat:
    path: /usr/bin/authselect
  register: result_authselect_present

- name: "Remediation where authselect tool is present"
  block:
    - name: Check the integrity of the current authselect profile
      ansible.builtin.command:
        cmd: authselect check
      register: result_authselect_check_cmd
      changed_when: false
      ignore_errors: true

    - name: Informative message based on the authselect integrity check result
      ansible.builtin.assert:
        that:
          - result_authselect_check_cmd is success
        fail_msg:
        - authselect integrity check failed. Remediation aborted!
        - This remediation could not be applied because the authselect profile is not intact.
        - It is not recommended to manually edit the PAM files when authselect is available.
        - In cases where the default authselect profile does not cover a specific demand, a custom authselect profile is recommended.
        success_msg:
        - authselect integrity check passed

    - name: Get authselect current profile
      ansible.builtin.shell:
        cmd: authselect current -r | awk '{ print $1 }'
      register: result_authselect_profile
      changed_when: false
      when:
        - result_authselect_check_cmd is success

{{% if product in ["ol8"] %}}
    - name: Define the current authselect profile as a local fact
      ansible.builtin.set_fact:
        authselect_current_profile: "{{ result_authselect_profile.stdout }}"
        authselect_custom_profile: "{{ result_authselect_profile.stdout }}"
      when:
        - result_authselect_profile is not skipped
        - result_authselect_profile.stdout is match("custom/")

    - name: Define the new authselect custom profile as a local fact
      ansible.builtin.set_fact:
        authselect_current_profile: "{{ result_authselect_profile.stdout }}"
        authselect_custom_profile: "custom/hardening"
      when:
        - result_authselect_profile is not skipped
        - result_authselect_profile.stdout is not match("custom/")

    - name: Get authselect current features to also enable them in the custom profile
      ansible.builtin.shell:
        cmd: authselect current | tail -n+3 | awk '{ print $2 }'
      register: result_authselect_features
      changed_when: false
      when:
        - result_authselect_profile is not skipped
        - authselect_current_profile is not match("custom/")

    - name: Check if any custom profile with the same name was already created in the past
      ansible.builtin.stat:
        path: /etc/authselect/{{ authselect_custom_profile }}
      register: result_authselect_custom_profile_present
      changed_when: false
      when:
        - authselect_current_profile is not match("custom/")

    - name: Create a custom profile based on the current profile
      ansible.builtin.command:
        cmd: authselect create-profile hardening -b sssd
      when:
        - result_authselect_check_cmd is success
        - authselect_current_profile is not match("custom/")
        - not result_authselect_custom_profile_present.stat.exists

    - name: Ensure the desired configuration is present in the custom profile smartcard-auth
      ansible.builtin.lineinfile:
        create: true
        dest: "/etc/authselect/{{ authselect_custom_profile }}/smartcard-auth"
        insertbefore: ^session.*
        firstmatch: yes
        regexp: '^(\s*auth.*pam_sss\.so)$'
        line: "auth     sufficient                   pam_sss.so try_cert_auth"
      when:
        - result_authselect_profile is not skipped
    
    - name: Ensure the desired configuration is present in the custom profile system-auth
      ansible.builtin.lineinfile:
        create: true
        dest: "/etc/authselect/{{ authselect_custom_profile }}/system-auth"
        insertbefore: ^session.*
        firstmatch: yes
        regexp: '^(\s*auth.*pam_sss\.so)$'
        line: "auth     sufficient                   pam_sss.so try_cert_auth"
      when:
        - result_authselect_profile is not skipped

    - name: Ensure the try_cert_auth option is in smartcard-auth
      ansible.builtin.replace:
        dest: "/etc/authselect/{{ authselect_custom_profile }}/smartcard-auth"
        regexp: '^(\s*auth.*pam_sss\.so)((?!try_cert_auth).)*$'
        replace: '\g<1> try_cert_auth \g<2>'
      when:
        - result_authselect_profile is not skipped
        - result_pam_try_cert_auth_present_smartcard_auth.found == 0

    - name: Ensure the try_cert_auth option is in system-auth
      ansible.builtin.replace:
        dest: "/etc/authselect/{{ authselect_custom_profile }}/system-auth"
        regexp: '^(\s*auth.*pam_sss\.so)((?!try_cert_auth).)*$'
        replace: '\g<1> try_cert_auth \g<2>'
      when:
        - result_authselect_profile is not skipped
        - result_pam_try_cert_auth_present_system_auth.found == 0

    - name: Ensure a backup of current authselect profile before selecting the custom profile
      ansible.builtin.command:
        cmd: authselect apply-changes -b --backup=before-pwhistory-hardening.backup
      register: result_authselect_backup
      when:
        - result_authselect_check_cmd is success
        - result_authselect_profile is not skipped
        - authselect_current_profile is not match("custom/")
        - authselect_custom_profile is not match(authselect_current_profile)

    - name: Ensure the custom profile is selected
      ansible.builtin.command:
        cmd: authselect select {{ authselect_custom_profile }} --force
      register: result_pam_authselect_select_profile
      when:
        - result_authselect_check_cmd is success
        - result_authselect_profile is not skipped
        - authselect_current_profile is not match("custom/")
        - authselect_custom_profile is not match(authselect_current_profile)

    - name: Restore the authselect features in the custom profile
      ansible.builtin.command:
        cmd: authselect enable-feature {{ item }}
      loop: "{{ result_authselect_features.stdout_lines }}"
      when:
        - result_authselect_profile is not skipped
        - result_authselect_features is not skipped
        - result_pam_authselect_select_profile is not skipped
{{% else %}}
    - name: Get authselect current features
      ansible.builtin.shell:
        cmd: authselect current | tail -n+3 | awk '{ print $2 }'
      register: result_authselect_features
      changed_when: false
      when:
        - result_authselect_check_cmd is success
        - result_authselect_profile is not skipped

    - name: Ensure smartcards are enabled via authselect tool
      ansible.builtin.command:
        cmd: authselect enable-feature with-smartcard
      when:
        - result_authselect_check_cmd is success
        - result_authselect_features.stdout is not search("with-smartcard")
        - result_authselect_profile is not skipped
{{% endif %}}
    - name: Ensure the custom profile changes are applied
      ansible.builtin.command:
        cmd: authselect apply-changes -b --backup=after-pwhistory-hardening.backup
      when:
        - result_authselect_check_cmd is success
        - result_authselect_profile is not skipped
  when:
    - (result_pam_try_cert_auth_present_smartcard_auth.found == 0) or (result_pam_try_cert_auth_present_system_auth.found == 0)
    - result_authselect_present.stat.exists

# For systems without authselect
- name: "Remediation where authselect tool is not present and PAM files are directly edited"
  block:
    - name: Ensure the desired configuration is present in the custom profile smartcard-auth
      ansible.builtin.lineinfile:
        create: true
        dest: "/etc/pam.d/smartcard-auth"
        insertbefore: ^session.*
        firstmatch: yes
        regexp: '^(\s*auth.*pam_sss\.so)$'
        line: "auth     sufficient                   pam_sss.so try_cert_auth"
    
    - name: Ensure the desired configuration is present in the custom profile system-auth
      ansible.builtin.lineinfile:
        create: true
        dest: "/etc/pam.d/system-auth"
        insertbefore: ^session.*
        firstmatch: yes
        regexp: '^(\s*auth.*pam_sss\.so)$'
        line: "auth     sufficient                   pam_sss.so try_cert_auth"

    - name: Ensure the try_cert_auth option is in smartcard-auth
      ansible.builtin.replace:
        dest: "/etc/pam.d/smartcard-auth"
        regexp: '^(auth.*sufficient.*pam_sss\.so)((?!try_cert_auth).)*$'
        replace: '\g<1> try_cert_auth \g<2>'
      when:
        - result_pam_try_cert_auth_present_smartcard_auth.found == 0

    - name: Ensure the try_cert_auth option is in system-auth
      ansible.builtin.replace:
        dest: "/etc/pam.d/system-auth"
        regexp: '^(auth.*sufficient.*pam_sss\.so)((?!try_cert_auth).)*$'
        replace: '\g<1> try_cert_auth \g<2>'
      when:
          - result_pam_try_cert_auth_present_system_auth.found == 0
  when:
    - (result_pam_try_cert_auth_present_smartcard_auth.found == 0) or (result_pam_try_cert_auth_present_system_auth.found == 0)
    - not result_authselect_present.stat.exists
{{% endif %}}
