# platform = multi_platform_rhel,multi_platform_ol,multi_platform_rhv
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ ansible_sshd_set(parameter="PrintLastLog", value="yes") }}}
