# platform = multi_platform_all
# reboot = true
# strategy = disable
# complexity = low
# disruption = medium
- name: List /etc/sysctl.d/*.conf files
  find:
    paths:
    - /etc/sysctl.d/
    - /run/sysctl.d/
    contains: ^[\s]*kernel.core_pattern.*$
    patterns: '*.conf'
    file_type: any
  register: find_sysctl_d
- name: Comment out any occurrences of kernel.core_pattern from /etc/sysctl.d/*.conf
    files
  replace:
    path: '{{ item.path }}'
    regexp: ^[\s]*kernel.core_pattern
    replace: '#kernel.core_pattern'
  loop: '{{ find_sysctl_d.files }}'
- name: Comment out any occurrences of kernel.core_pattern with value from /etc/sysctl.conf files
  replace:
    path: /etc/sysctl.conf
    regexp: ^[\s]*kernel.core_pattern[[:blank:]]*=[[:blank:]]*\S+
    replace: '#kernel.core_pattern'
- name: Ensure sysctl kernel.core_pattern is set to empty
  sysctl:
    name: kernel.core_pattern
    value: ' ' # ansible sysctl module doesn't allow empty string, a space string is allowed and has the same semantics as sysctl will ignore spaces
    state: present
    reload: true
