product: fuse6

benchmark_root: "./guide"

profiles_root: "./profiles"

platform_cpes:
  - "cpe:/a:redhat:jboss_fuse:6.0"
  - "cpe:/a:redhat:jboss_fuse:6.1.0"
  - "cpe:/a:redhat:jboss_fuse_service_works:6.0"
