# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Ensure AIDE is installed"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - aide

- name: "{{{ rule_title }}}"
  cron:
    name: "run AIDE check"
    minute: 05
    hour: 04
    weekday: 0
    user: root
    job: "{{{ aide_bin_path }}} --check"
