# platform = multi_platform_sle
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ ansible_instantiate_variables("var_accounts_password_warn_age_login_defs") }}}

- name: Collect users with not correct number of days of warning before password expires
  ansible.builtin.command:
    cmd: awk -F':' '$6 < {{ var_accounts_password_warn_age_login_defs }} || $6 == "" {print $1}' /etc/shadow
  register: user_names

- name: Change the number of days of warning before password expires
  ansible.builtin.command:
    cmd: chage --warndays {{ var_accounts_password_warn_age_login_defs }} {{ item }}
  with_items: '{{ user_names.stdout_lines }}'
  when: user_names.stdout_lines | length > 0
