# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

{{{ ansible_instantiate_variables("var_accounts_max_concurrent_login_sessions") }}}

- name: Find /etc/security/limits.d files contains maxlogins configuration
  shell: "grep -q '^[^#]*\\<maxlogins\\>' /etc/security/limits.d/*.conf"
  register: maxlogins
  failed_when: False

- name: Find /etc/security/limits.d files contains maxlogins configuration 2
  find:
    paths:
      - /etc/security/limits.d
  register: configuration_files
  when: maxlogins.rc == 0

- name: "Limit the Number of Concurrent Login Sessions Allowed Per User limits.d"
  replace:
    dest: "{{ item.path }}"
    regexp: "^#?\\*.*maxlogins.*"
    replace: "*          hard    maxlogins     {{ var_accounts_max_concurrent_login_sessions }}"
  with_items:
    - "{{ configuration_files.files }}"
  when: maxlogins.rc == 0

- name: "Limit the Number of Concurrent Login Sessions Allowed Per User"
  lineinfile:
    state: present
    dest: /etc/security/limits.conf
    insertbefore: "^# End of file"
    regexp: "^#?\\*.*maxlogins"
    line: "*          hard    maxlogins     {{ var_accounts_max_concurrent_login_sessions }}"
    create: yes
  when: maxlogins.rc != 0 # no files found on /etc/security/limits.d
