product: rhel6

benchmark_root: "./guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "upstart"

cpes:
  - "cpe:/o:redhat:enterprise_linux:6"
  - "cpe:/o:redhat:enterprise_linux:6::client"
  - "cpe:/o:redhat:enterprise_linux:6::computenode"

full_name: Red Hat Enterprise Linux 6
