product: rhel6
full_name: Red Hat Enterprise Linux 6
type: platform

benchmark_root: "./guide"

profiles_root: "./profiles"

pkg_manager: "yum"

init_system: "upstart"

cpes:
  - "cpe:/o:redhat:enterprise_linux:6"
  - "cpe:/o:redhat:enterprise_linux:6::client"
  - "cpe:/o:redhat:enterprise_linux:6::computenode"

uid_min: 500 # sets the starting value for user ids, also used to set auid
