# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = high
# disruption = medium
- name: "Read list of files with incorrect ownership"
  shell: "rpm -Va --nofiledigest | grep "^.....\(U\|.G\)" | awk '{print $NF}'"
  register: files_with_incorrect_ownership
  failed_when: False
  changed_when: False
  check_mode: no
  tags:
    @ANSIBLE_TAGS@
    
- name: Create list of uniq packages
  shell: "rpm -qf {{ files_with_incorrect_ownership.stdout_lines }}|sort |uniq"
  register: uniq_list_of_packages
  when: files_with_incorrect_ownership.stdout_lines | length > 0
  tags:
    @ANSIBLE_TAGS@

- name: "Correct file ownership with RPM"
  shell: "rpm --quiet --setugids '{{item}}'"
  with_items: "{{ uniq_list_of_packages.stdout_lines }}"
  when: files_with_incorrect_ownership.stdout_lines | length > 0
  tags:
    @ANSIBLE_TAGS@
