# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

{{{ ansible_set_config_file(file='/etc/chrony.conf', parameter='cmdport', separator=' ', value='0', create='yes') }}}
