product: ubuntu1604

benchmark_root: "../debian8/guide"

profiles_root: "./profiles"

pkg_manager: "apt_get"

init_system: "systemd"

cpes:
  - "cpe:/o:canonical:ubuntu_linux:16.04"

full_name: "Ubuntu 16.04"
