# platform = multi_platform_sle,multi_platform_ubuntu
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

{{{ ansible_instantiate_variables("var_pam_wheel_group_for_su") }}}

- name: {{{ rule_title }}} - Ensure group {{ var_pam_wheel_group_for_su }} is removed
  group:
    name: "{{ var_pam_wheel_group_for_su }}"
    state: absent 

- name: {{{ rule_title }}} - Ensure group {{ var_pam_wheel_group_for_su }} exist
  group:
    name: "{{ var_pam_wheel_group_for_su }}"
    state: present

- name: {{{ rule_title }}} - Add the group to the /etc/pam.d/su file
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/su"
    state: present
    regexp: '^[\s]*#[\s]*auth[\s]+required[\s]+pam_wheel\.so[\s]+use_uid group=$'
    line: "auth             required        pam_wheel.so use_uid group={{ var_pam_wheel_group_for_su }}"
