# platform=multi_platform_rhel,multi_platform_ol,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "Ensure owner on /etc/ssh/sshd_config is configured"
  file:
    path: /etc/ssh/sshd_config
    group: "root"

