# platform = multi_platform_all
# reboot = true
# strategy = restrict
# complexity = low
# disruption = low

{{% if 'sle' in product %}}
- name: Verify that Interactive Boot is Disabled in /usr/bin/grub2-editenv
  replace:
    dest: /etc/default/grub
    regexp: systemd.confirm_spawn=(1|yes|true|on) 
    replace: systemd.confirm_spawn=no

- name: Verify that Interactive Boot is Disabled (runtime)
  command: /usr/bin/grub2-editenv - unset systemd.confirm_spawn

- name: Veify GRUB_DISABLE_RECOVERY=true
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DISABLE_RECOVERY=.*'
    line: 'GRUB_DISABLE_RECOVERY=true'
    state: present

- name: Verify that Recovery Boot is Disabled (runtime)
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

{{% else %}}

- name: Verify that Interactive Boot is Disabled in /etc/default/grub
  replace:
    dest: /etc/default/grub
    regexp: systemd.confirm_spawn=(1|yes|true|on)
    replace: systemd.confirm_spawn=no

- name: Verify that Interactive Boot is Disabled (runtime)
  command: /sbin/grubby --update-kernel=ALL --remove-args="systemd.confirm_spawn"

{{% endif %}}
