# platform = multi_platform_fedora,Red Hat Enterprise Linux 7
# reboot = false
# strategy = configure
# complexity = low
# disruption = low

- name: "detect if file is not empty or missing"
  find:
    register: num_matched
    path: /etc/sysconfig/ntpd
    contains: '^([\s]*OPTIONS=["]?[^"]*)("?)'

- name: "replace existing setting or create a new file, rest is handled by different task"
  lineinfile:
    path: /etc/sysconfig/ntpd
    regexp: '^([\s]*OPTIONS=["]?[^"]*)("?)'
    line: '\1 -u ntp:ntp\2'
    state: present
    create: yes
    backrefs: true
    when: nam_matched > 0

- name: "put line into file, assume file was empty"
  lineinfile:
  path: /etc/sysconfig/ntpd
  line: 'OPTIONS="-u ntp:ntp"'
  state: present
  when: num_matched == 0
