product: fedora

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "dnf"

init_system: "systemd"

platform_cpes:
  - "cpe:/o:fedoraproject:fedora:28"
  - "cpe:/o:fedoraproject:fedora:27"
  - "cpe:/o:fedoraproject:fedora:26"
  - "cpe:/o:fedoraproject:fedora:25"
