product: fedora
full_name: Fedora
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "dnf"

init_system: "systemd"

# The fingerprints below are retrieved from https://getfedora.org/keys/
latest_version: 29
latest_release_fingerprint: "5A03 B4DD 8254 ECA0 2FDA  1637 A20A A56B 4294 76B4"
latest_pkg_release: 5a886537
latest_pkg_version: 429476b4

previous_version: 28
previous_release_fingerprint: "128C F232 A937 1991 C8A6  5695 E08E 7E62 9DB6 2FB1"
previous_pkg_release: 59920156
previous_pkg_version: 9db62fb1
