# platform = multi_platform_all
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium

- name: "Check if NetworkManager is installed"
  package_facts:
    manager: "auto"

- name: Deactivate Wireless Network Interfaces
  command: nmcli radio wifi off
  when: "'NetworkManager' in ansible_facts.packages"

