# platform = multi_platform_fedora
# reboot = true
# strategy = configure
# complexity = low
# disruption = low

- name: "@RULE_TITLE@"
  file:
    src: /etc/crypto-policies/back-ends/krb5.config
    path: /etc/krb5.conf.d/crypto-policies
    state: link
  tags:
    @ANSIBLE_TAGS@
