# platform = multi_platform_rhel, multi_platform_fedora
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- (xccdf-var sshd_idle_timeout_value)

- name: "Configure SSSD to Expire SSH Known Hosts"
  ini_file:
    dest: /etc/sssd/sssd.conf
    section: ssh
    option: ssh_known_hosts_timeout
    value: "{{ sshd_idle_timeout_value }}"
    create: yes
    mode: 0600
