# platform = multi_platform_sle
# reboot = false
# strategy = configure
# complexity = low
# disruption = low

- name: Check to see if 'sha512' parameter is present
  shell: |
    grep -e '^\s*auth\s\+[a-z]+\s\+pam_unix\.so.*sha512.*' /etc/pam.d/common-auth | cat
  register: check_pam_unix_sha512_result

- name: Make sure pam_unix.so has 'sha512' parameter set
  replace:
    path: /etc/pam.d/common-auth
    regexp: ^(\s*auth\s+[a-z]+\s+pam_unix\.so\s+[^\n]*)([^A-Za-z]?.*)
    replace: '\1 sha512 \2'
  register: pam_unix_sha512_result
  when: '"sha512" not in check_pam_unix_sha512_result.stdout'

- name: Check to see if pam_unix.so is required
  shell: |
    grep -e '^\s*auth\s\+required\s\+pam_unix\.so.*' /etc/pam.d/common-auth | cat
  register: check_pam_unix_required_result

- name: Make sure pam_unix.so is required
  replace:
    path: /etc/pam.d/common-auth
    regexp: ^(\s*auth\s+)([a-z]+)(\s+pam_unix\.so\s+[^\n]*[^A-Za-z]?.*)
    replace: '\1required\3'
  register: pam_unix_required_result
  when: '"required" not in check_pam_unix_required_result.stdout'
