# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
{{{ ansible_sshd_set(parameter="X11Forwarding", value="yes") }}}
