# platform = multi_platform_rhel, multi_platform_fedora
# reboot = false
# strategy = enable
# complexity = low
# disruption = low
- name: Ensure dracut-fips is installed
  package:
    name: dracut-fips
    state: present
    when: ansible_distribution == 'Red Hat Enterprise Linux' and @ANSIBLE_PLATFORM_CONDITION@
  tags:
    @ANSIBLE_TAGS@
