name: "cpe:/a:{arg}:{ver_specs_cpe}"
title: "Package {pkgname} is installed"
bash_conditional: {{{ bash_pkg_conditional("{pkgname}", escape=True) }}}
ansible_conditional: {{{ ansible_pkg_conditional("{pkgname}") }}}
versioned: true
template:
  name: platform_package
args:
  audit:
    {{% if 'ubuntu' in product or 'debian' in product %}}
    pkgname: auditd
    {{% else %}}
    pkgname: audit
    {{% endif %}}
  chrony:
    pkgname: chrony
  gdm:
    {{% if pkg_system == "rpm" %}}
    pkgname: gdm
    {{% else %}}
    pkgname: gdm3
    {{% endif %}}
  libuser:
    pkgname: libuser
  ntp:
    pkgname: ntp
    title: NTP daemon and utilities
