name: "cpe:/a:{arg}"
title: "Package {pkgname} is installed"
bash_conditional: {{{ bash_pkg_conditional("{pkgname}") }}}
ansible_conditional: {{{ ansible_pkg_conditional("{pkgname}") }}}
check_id: cond_package_{arg}
template:
  name: cond_package
args:
  ntp:
    pkgname: ntp
    title: NTP daemon and utilities
