# platform = multi_platform_rhel,multi_platform_fedora,multi_platform_ol
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- (xccdf-var login_banner_text)

- name: "{{{ rule_title }}}"
  lineinfile:
    dest: /etc/issue
    line: '{{{ ansible_deregexify_banner_etc_issue("login_banner_text") }}}'
    create: yes
