# platform = multi_platform_all

{{{ ansible_set_config_file(file="/etc/aliases",
                            parameter='postmaster',
                            separator=': ',
                            separator_regex='\s*:\s*',
                            value='root',
                            create='yes') }}}

- name: Update postfix aliases
  ansible.builtin.command:
    cmd: newaliases

