# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_ol
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

{{%- if product in ["rhel7", "ol7"] %}}
  {{%- set auditd_conf_path=audisp_conf_path + "/audispd.conf" %}}
{{%- else %}}
  {{%- set auditd_conf_path=audisp_conf_path + "/auditd.conf" %}}
{{%- endif %}}

{{{ ansible_instantiate_variables("var_auditd_name_format") }}}

- name: Set type of computer node name logging in audit logs
  block:
  - name: Check for duplicate values
    lineinfile:
      path: "{{{ auditd_conf_path }}}"
      create: true
      regexp: (?i)^\s*name_format\s*=\s*
      state: absent
    check_mode: true
    changed_when: false
    register: dupes

  - name: Deduplicate values from {{{ auditd_conf_path }}}
    lineinfile:
      path: "{{{ auditd_conf_path }}}"
      create: true
      regexp: (?i)^\s*name_format\s*=\s*
      state: absent
    when: dupes.found is defined and dupes.found > 1

  - name: Insert correct line to {{{ auditd_conf_path }}}
    lineinfile:
      path: "{{{ auditd_conf_path }}}"
      create: true
      regexp: (?i)^\s*name_format\s*=\s*
      line: name_format = {{ var_auditd_name_format.split('|')[0] }}
      state: present
