product: ocp3

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_system: "rpm"

init_system: "systemd"

platform_cpes:
  - "cpe:/a:redhat:openshift:3.0"
  - "cpe:/a:redhat:openshift:3.1"
