product: ocp3
full_name: Red Hat Enterprise OpenShift Container Platform 3
type: platform

benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_system: "rpm"

init_system: "systemd"

cpes:
  - "cpe:/a:redhat:openshift:3.0"
  - "cpe:/a:redhat:openshift:3.1"
