name: Build and Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  validate-ubuntu:
    name: Build Content (Ubuntu 20.04 / VM)
    runs-on: ubuntu-20.04
    steps:
      - name: Install Deps
        uses: mstksg/get-package@master
        with:
          apt-get: cmake ninja-build libopenscap8 libxml2-utils expat xsltproc python3-jinja2 python3-yaml ansible-lint python3-github
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./build_product chromium fedora firefox fuse6 rhcos4 rhel7 rhel8 rhel9 rhosp10 rhosp13 sle12 sle15 ubuntu2004
      - name: Test
        run: ctest -j2 --output-on-failure -E unique-stigids
        working-directory: ./build
      - name: Build Ansible Roles
        run: PYTHONPATH=. python3 utils/ansible_playbook_to_role.py --build-playbooks-dir ./build/ansible/ --dry-run ./build/ansible_roles
      - name: Lint Ansible Roles
        run: ansible-lint -x 204 -x experimental ./build/ansible_roles/*

  validate-fedora:
    name: Build Content (Fedora 33 / Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:33
    steps:
      - name: Install Deps
        run: dnf install -y cmake make openscap-utils python3-pyyaml python3-jinja2
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./build_product chromium fedora firefox fuse6 rhcos4 rhel7 rhel8 rhel9 rhosp10 rhosp13 sle12 sle15 ubuntu2004 ocp4
      - name: Test
        run: ctest -j2 --output-on-failure -E unique-stigids
        working-directory: ./build
