---
name: Kubernetes content

on:
  push:
    branches: [ 'master' ]

jobs:
  container-main:
    permissions:
      id-token: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: k8scontent
      tag: latest
      registry_org: complianceascode
      dockerfile_path: ./Dockerfiles/ocp4_content
      licenses: BSD
      vendor: ComplianceAsCode authors
